[global]
debug = true

domain = boehringer-ingelheim.com
apply_policy = true

enable_hello = true
hello_pin_min_length = 6
hello_pin_retry_count = 3
entra_id_password_prompt = Enter your Boehringer Ingelheim password.

local_groups = wheel,docker,incus-admin,libvirt # grant sudo access to all EntraID users

# Ensure that the TPM is used for key storage and attestation
hsm_type = tpm

# optional script with access to access token variables
# logon_script = /etc/himmelblau/logon.sh
# cn_name_mapping = true
# home_attr = UUID
# home_alias = CN
# pam_allow_groups =
# local_sudo_group = wheel
# sudo_groups = <ids of EntraID groups>
# enable_sfa_fallback = false
# allow_console_password_only = true
# enable_passwordless = false # prompt users for password, then MFA. Set to true to allow passwordless logins with MFA only. Currently disabled as MFA takes a long time.
# idmap_range = 5000000-5999999

# enable offline authentication, in case EntraId/Internet is not available
[offline_breakglass]
enabled = true
ttl = 5d