[global]
domain = boehringer-ingelheim.com
apply_policy = true

local_sudo_group = wheel

# pam_allow_groups
enable_hello = true
hello_pin_min_length = 6
hello_pin_retry_count = 3
entra_id_password_prompt = Enter your Boehringer Ingelheim password.
enable_sfa_fallback = false
# allow_console_password_only = true

# cn_name_mapping = true
local_groups = wheel # grant sudo access to all EntraID users
# local_sudo_group
# home_attr = UUID
# home_alias = CN

idmap_range = 5000000-5999999

# enable offline authentication, in case EntraId is not reachable
[offline_breakglass]
enabled = true
ttl = 7d